[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base =

# Primary accent color for interactive elements.
primaryColor = #FF584B

# Background color for the main content area.
backgroundColor = #181F2D

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = #181F2D

# Color used for almost all text.
textColor = #181F2D

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"